# Generated by Django 4.2.2 on 2023-07-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='profesion',
            new_name='pais',
        ),
    ]
