# Generated by Django 4.2.2 on 2023-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_profesion_profesor_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='camada',
        ),
        migrations.AddField(
            model_name='curso',
            name='apellido',
            field=models.CharField(default='Sin Apellido', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='pais',
            field=models.CharField(default='Sin Pais', max_length=40, null=True),
        ),
    ]
