# Generated by Django 4.2.2 on 2023-07-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_remove_curso_camada_curso_apellido_curso_pais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Lideres',
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Fans', 'verbose_name_plural': 'Fans'},
        ),
        migrations.AlterModelOptions(
            name='entregable',
            options={'verbose_name': 'Construyentes', 'verbose_name_plural': 'Construyentes'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Dream Achievers', 'verbose_name_plural': 'Dream Achievers'},
        ),
        migrations.AlterModelOptions(
            name='lideres',
            options={'verbose_name': 'Lideres', 'verbose_name_plural': 'Lideres'},
        ),
    ]
