# Generated by Django 4.2.2 on 2023-08-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_profesor_lideres_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Fans',
        ),
    ]
